/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-keyword-ranking",
  templateUrl: "./KeywordRanking.component.html",
  styleUrls: ["./KeywordRanking.component.scss"],
})
export class KeywordRankingComponent {}
