/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-keyword-sales-dashboard",
  templateUrl: "./KeywordSalesDashboard.component.html",
  styleUrls: ["./KeywordSalesDashboard.component.scss"],
})
export class KeywordSalesDashboardComponent {}
