/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { KeywordSalesDashboardComponent } from "./KeywordSalesDashboard.component";
import { SalesOverviewComponent } from "./sales-overview/SalesOverview.component";
import { TopProductsComponent } from "./top-products/TopProducts.component";
import { TargetVsRealityComponent } from "./target-vs-reality/TargetVsReality.component";
import { KeywordRankingComponent } from "./keyword-ranking/KeywordRanking.component";
import { OrganicRankingComponent } from "./organic-ranking/OrganicRanking.component";

@NgModule({
  declarations: [
    KeywordSalesDashboardComponent,
    SalesOverviewComponent,
    TopProductsComponent,
    TargetVsRealityComponent,
    KeywordRankingComponent,
    OrganicRankingComponent,
  ],
  imports: [CommonModule],
  exports: [KeywordSalesDashboardComponent],
})
export class KeywordSalesDashboardModule {}
