/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-keyword-sales-dashboard",
  templateUrl: "./keyword-sales-dashboard.component.html",
  styleUrls: ["./keyword-sales-dashboard.component.scss"],
})
export class KeywordSalesDashboardComponent {}
