/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "keyword-ranking",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="keyword-ranking">
      <h2 class="keyword-ranking__title">Keyword Ranking</h2>
      <div class="keyword-ranking__products">
        <span class="keyword-ranking__product">SMELLWELL ACTIVE</span>
        <span class="keyword-ranking__product">Black Zebra</span>
      </div>
      <h3 class="keyword-ranking__subtitle">Clicks per Keyword</h3>
      <div class="keyword-ranking__chart">
        <!-- Chart content would go here -->
      </div>
      <div class="keyword-ranking__x-axis">
        <span>Shoe Smell</span>
        <span>Odor Eliminator</span>
        <span>Clean Smell Bag</span>
        <span>Smell Balls</span>
        <span>Odor Exterminator</span>
        <span>Smell Bag</span>
        <span>Odor Bag</span>
      </div>
      <div class="keyword-ranking__legend">
        <div class="legend-item">
          <span class="legend-item__color legend-item__color--this-month"></span>
          <span class="legend-item__label">This Month</span>
        </div>
        <div class="legend-item">
          <span class="legend-item__color legend-item__color--last-month"></span>
          <span class="legend-item__label">Last Month</span>
        </div>
      </div>
    </section>
  `,
  styles: [`
    .keyword-ranking {
      background-color: #fff;
      border-radius: 1.25rem;
      box-shadow: 0 0.25rem 1.25rem rgba(238, 238, 238, 0.502);
      padding: 2.625rem 1.3125rem;
      border: 1px solid #f8f9fa;
    }

    .keyword-ranking__title {
      color: #05004e;
      font: 600 1.25rem/1.6 Poppins, sans-serif;
      margin: 0;
    }

    .keyword-ranking__products {
      display: flex;
      gap: 1.25rem;
      margin-top: 1rem;
    }

    .keyword-ranking__product {
      color: #000;
      font: 400 1.25rem/1 Rajdhani, sans-serif;
    }

    .keyword-ranking__subtitle {
      color: #737791;
      font: 300 1rem/2 Poppins, sans-serif;
      margin: 2.5625rem 0 0;
    }

    .keyword-ranking__chart {
      height: 18.75rem;
      margin: 1.6875rem 0;
      /* Chart styles would go here */
    }

    .keyword-ranking__x-axis {
      display: flex;
      justify-content: space-between;
      color: #7b91b0;
      font: 400 0.75rem/1 Poppins, sans-serif;
      margin-bottom: 4.875rem;
    }

    .keyword-ranking__legend {
      display: flex;
      gap: 8.125rem;
      justify-content: center;
    }

    .legend-item {
      display: flex;
      align-items: center;
      gap: 0.8125rem;
    }

    .legend-item__color {
      width: 1.5rem;
      height: 1.5rem;
      border-radius: 0.375rem;
    }

    .legend-item__color--this-month {
      background-color: #0095ff;
    }

    .legend-item__color--last-month {
      background-color: #00e096;
    }

    .legend-item__label {
      color: #222b45;
      font: 400 0.75rem/1 Open Sans, sans-serif;
    }
  `]
})
export class KeywordRanking {}