/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "organic-ranking",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="organic-ranking">
      <h2 class="organic-ranking__title">
        Organic Ranking
        <span class="organic-ranking__subtitle">Top Keywords</span>
      </h2>
      <div class="organic-ranking__products">
        <span class="organic-ranking__product">SMELLWELL ACTIVE</span>
        <span class="organic-ranking__product">Black Zebra</span>
      </div>
      <table class="organic-ranking__table">
        <thead>
          <tr>
            <th>#</th>
            <th>Keyword</th>
            <th>Organic Rank</th>
            <th>Monthly Sales</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Shoe Smell</td>
            <td>
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/0c25a4d0b2c797f3b81956ff13e384c53fdf00cc4cd8a418c24cfbdf30104fa2?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="organic-ranking__rank-icon" />
              1
            </td>
            <td>2430$</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Odor Eliminator</td>
            <td>
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b3855c5524201bd8e71d9d8640cacf57cfdb2398aed9e2a979c6201ff65cfe9?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="organic-ranking__rank-icon" />
              2
            </td>
            <td>1967$</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Smell Balls</td>
            <td>
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/92bacaf9db33d86434387d3c7396ba1b77a00ef1c54f7274f5bd82ab49829e34?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="organic-ranking__rank-icon" />
              9
            </td>
            <td>1308$</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Clean Smell Bag</td>
            <td>
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/f1f0a1b976c37a276cd2a9c7d1e7cd789fe81d1b5da92bb4c7899cf1cd717164?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="organic-ranking__rank-icon" />
              17
            </td>
            <td>196$</td>
          </tr>
        </tbody>
      </table>
    </section>
  `,
  styles: [`
    .organic-ranking {
      background-color: #fff;
      border-radius: 1.25rem;
      box-shadow: 0 0.25rem 1.25rem rgba(238, 238, 238, 0.502);
      padding: 2.625rem 1.3125rem;
      border: 1px solid #f8f9fa;
    }

    .organic-ranking__title {
      color: #737791;
      font: 600 1.25rem/2 Poppins, sans-serif;
      margin: 0;
    }

    .organic-ranking__subtitle {
      display: block;
      font-weight: 400;
      font-size: 1rem;
      color: #737791;
    }

    .organic-ranking__products {
      display: flex;
      gap: 1.25rem;
      margin-top: 1rem;
    }

    .organic-ranking__product {
      color: #000;
      font: 400 1.25rem/1 Rajdhani, sans-serif;
    }

    .organic-ranking__table {
      width: 100%;
      border-collapse: separate;
      border-spacing: 0 1rem;
      margin-top: 2rem;
    }

    .organic-ranking__table th,
    .organic-ranking__table td {
      text-align: left;
      padding: 0.5rem 1rem;
    }

    .organic-ranking__table th {
      color: #96a5b8;
      font: 400 0.8125rem/1 Open Sans, sans-serif;
    }

    .organic-ranking__table td {
      color: #444a6d;
      font: 400 0.875rem/1 Poppins, sans-serif;
    }

    .organic-ranking__table tr {
      background-color: #fff;
    }

    .organic-ranking__table tbody tr {
      box-shadow: 0 0.25rem 0.25rem rgba(0, 0, 0, 0.05);
    }

    .organic-ranking__rank-icon {
      width: 1.5625rem;
      height: auto;
      margin-right: 0.4375rem;
      vertical-align: middle;
    }
  `]
})
export class OrganicRanking {}