/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "sales-overview",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="sales-overview">
      <h2 class="sales-overview__title">Monthly sales</h2>
      <p class="sales-overview__subtitle">Sales Summary</p>
      <div class="sales-overview__grid">
        <div class="sales-card sales-card--total">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/9c77f9e776b076fced5e3c695d978bc1593bb092065bd9cd60fa1557ad424ffe?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="sales-card__icon" />
          <p class="sales-card__value">$1k</p>
          <p class="sales-card__label">Total Sales</p>
          <p class="sales-card__change">+8% from last month</p>
        </div>
        <div class="sales-card sales-card--orders">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ee26bce610a00af2a0f87815a0d6cf8c35397eec44b2e685cfeb4e0b8773dca?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="sales-card__icon" />
          <p class="sales-card__value">300</p>
          <p class="sales-card__label">Total Order</p>
          <p class="sales-card__change">+8% from last month</p>
        </div>
        <div class="sales-card sales-card--products">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/a408a72f830e47f0deef7884d8389fd2313cec130e3a9d0d03defdc42a61f4eb?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="sales-card__icon" />
          <p class="sales-card__value">5</p>
          <p class="sales-card__label">Product Sold</p>
          <p class="sales-card__change">+8% from last month</p>
        </div>
      </div>
    </section>
  `,
  styles: [`
    .sales-overview {
      background-color: #fff;
      border-radius: 1.25rem;
      box-shadow: 0 0.25rem 1.25rem rgba(238, 238, 238, 0.502);
      padding: 1.75rem 1.9375rem;
      border: 1px solid #f8f9fa;
    }

    .sales-overview__title {
      color: #05004e;
      font: 600 1.25rem/1.6 Poppins, sans-serif;
      margin: 0;
    }

    .sales-overview__subtitle {
      color: #737791;
      font: 400 1rem/1.875 Poppins, -apple-system, Roboto, Helvetica, sans-serif;
      margin: 0.25rem 0 0;
    }

    .sales-overview__grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 1.25rem;
      margin-top: 2.6875rem;
    }

    .sales-card {
      border-radius: 1rem;
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      padding: 1.25rem;
      font-family: Poppins, sans-serif;
    }

    .sales-card--total {
      background-color: #ffe2e5;
    }

    .sales-card--orders {
      background-color: #fff4de;
    }

    .sales-card--products {
      background-color: #dcfce7;
    }

    .sales-card__icon {
      width: 2.5rem;
      height: 2.5rem;
    }

    .sales-card__value {
      color: #151d48;
      font-size: 1.5rem;
      font-weight: 600;
      margin: 1rem 0 0;
    }

    .sales-card__label {
      color: #425166;
      font-size: 1rem;
      margin: 0.5rem 0 0;
    }

    .sales-card__change {
      color: #4079ed;
      font-size: 0.75rem;
      margin: 0.5rem 0 0;
    }

    @media (max-width: 991px) {
      .sales-overview {
        padding: 1.25rem;
      }

      .sales-overview__grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class SalesOverview {}