/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "target-vs-reality",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="target-vs-reality">
      <h2 class="target-vs-reality__title">Target vs Reality</h2>
      <div class="target-vs-reality__chart">
        <!-- Chart content would go here -->
      </div>
      <div class="target-vs-reality__legend">
        <div class="legend-item">
          <div class="legend-item">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/35eb9ea45e288070fd1cd0c35152c5be24a0da3c65f014aadaa7c60f167a7b1c?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="legend-item__icon" />
          <span class="legend-item__label">Reality Sales</span>
        </div>
        <div class="legend-item">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/2b1c92f6-4df7-4eaa-af1f-901b2cafb2f3?placeholderIfAbsent=true&apiKey=0b48fe8e354b4d2f9b80496aa2074bf7" alt="" class="legend-item__icon" />
          <span class="legend-item__label">Target Sales</span>
        </div>
      </div>
      <div class="target-vs-reality__x-axis">
        <span>Jan</span>
        <span>Feb</span>
        <span>Mar</span>
        <span>Apr</span>
        <span>May</span>
        <span>June</span>
      </div>
      <div class="target-vs-reality__summary">
        <div class="summary-item">
          <span class="summary-item__label">This Month</span>
          <span class="summary-item__value summary-item__value--reality">8.823</span>
          <span class="summary-item__value summary-item__value--target">12.122</span>
        </div>
      </div>
    </section>
  `,
  styles: [`
    .target-vs-reality {
      background-color: #fff;
      border-radius: 1.25rem;
      box-shadow: 0 0.25rem 1.25rem rgba(238, 238, 238, 0.502);
      padding: 1.5625rem 1.6875rem;
      position: relative;
    }

    .target-vs-reality__title {
      color: #05004e;
      font: 600 1.25rem/1.6 Poppins, sans-serif;
      margin: 0 0 1.375rem;
    }

    .target-vs-reality__chart {
      height: 15.625rem;
      margin-bottom: 1.25rem;
      /* Chart styles would go here */
    }

    .target-vs-reality__legend {
      display: flex;
      gap: 1.25rem;
      margin-bottom: 1rem;
    }

    .legend-item {
      display: flex;
      align-items: center;
      gap: 0.875rem;
    }

    .legend-item__icon {
      width: 2.25rem;
      height: auto;
    }

    .legend-item__label {
      color: #151d48;
      font: 600 0.75rem/1 Poppins, sans-serif;
    }

    .target-vs-reality__x-axis {
      display: flex;
      justify-content: space-between;
      color: #7b91b0;
      font: 400 0.625rem/1.6 Poppins, sans-serif;
      margin-bottom: 1rem;
    }

    .target-vs-reality__summary {
      display: flex;
      justify-content: flex-end;
    }

    .summary-item {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
    }

    .summary-item__label {
      color: #7b91b0;
      font: 400 0.75rem/1 Poppins, sans-serif;
      margin-bottom: 0.5rem;
    }

    .summary-item__value {
      font: 500 0.875rem/1 Poppins, sans-serif;
    }

    .summary-item__value--reality {
      color: #27ae60;
    }

    .summary-item__value--target {
      color: #ffa412;
    }
  `]
})
export class TargetVsReality {}