/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "top-products",
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="top-products">
      <h2 class="top-products__title">Big Leaps</h2>
      <div class="top-products__header">
        <div class="top-products__column">#</div>
        <div class="top-products__column">Name</div>
        <div class="top-products__column">Popularity</div>
        <div class="top-products__column">Sales</div>
      </div>
      <ul class="top-products__list">
        <li class="top-products__item">
          <div class="top-products__rank">1</div>
          <div class="top-products__name">Shoe Smell</div>
          <div class="top-products__popularity">
            <div class="progress-bar">
              <div class="progress-bar__fill" style="width: 45%"></div>
            </div>
            <span class="top-products__percentage">45%</span>
          </div>
        </li>
        <li class="top-products__item">
          <div class="top-products__rank">2</div>
          <div class="top-products__name">Odor Eliminator</div>
          <div class="top-products__popularity">
            <div class="progress-bar">
              <div class="progress-bar__fill" style="width: 29%"></div>
            </div>
            <span class="top-products__percentage">29%</span>
          </div>
        </li>
        <li class="top-products__item">
          <div class="top-products__rank">3</div>
          <div class="top-products__name">Smell Ball</div>
          <div class="top-products__popularity">
            <div class="progress-bar">
              <div class="progress-bar__fill" style="width: 18%"></div>
            </div>
            <span class="top-products__percentage">18%</span>
          </div>
        </li>
        <li class="top-products__item">
          <div class="top-products__rank">4</div>
          <div class="top-products__name">Clean Smelly Bag</div>
          <div class="top-products__popularity">
            <div class="progress-bar">
              <div class="progress-bar__fill" style="width: 25%"></div>
            </div>
            <span class="top-products__percentage">25%</span>
          </div>
        </li>
      </ul>
    </section>
  `,
  styles: [`
    .top-products {
      background-color: #fff;
      border-radius: 1.25rem;
      box-shadow: 0 0.25rem 1.25rem rgba(238, 238, 238, 0.502);
      padding: 1.375rem 0;
      border: 1px solid #f8f9fa;
    }

    .top-products__title {
      color: #05004e;
      font: 600 1.25rem/1.6 Poppins, sans-serif;
      margin: 0 0 1.125rem 1.25rem;
    }

    .top-products__header {
      display: flex;
      justify-content: space-between;
      padding: 0 1.25rem;
      margin-bottom: 0.9375rem;
    }

    .top-products__column {
      color: #96a5b8;
      font: 400 0.8125rem/1 Open Sans, sans-serif;
    }

    .top-products__list {
      list-style-type: none;
      padding: 0;
      margin: 0;
    }

    .top-products__item {
      display: flex;
      align-items: center;
      padding: 1.125rem 1.25rem;
      border-top: 1px solid #edf2f6;
    }

    .top-products__rank {
      color: #444a6d;
      font: 400 0.875rem/1 Poppins, sans-serif;
      width: 1.5rem;
    }

    .top-products__name {
      color: #444a6d;
      font: 400 0.875rem/1 Poppins, sans-serif;
      flex: 1;
    }

    .top-products__popularity {
      display: flex;
      align-items: center;
      gap: 0.625rem;
    }

    .progress-bar {
      background-color: #cde7ff;
      border-radius: 0.5rem;
      height: 0.25rem;
      width: 8.6875rem;
    }

    .progress-bar__fill {
      background-color: #0095ff;
      border-radius: 0.5rem;
      height: 100%;
    }

    .top-products__percentage {
      background-color: #f0f9ff;
      border: 1px solid #0095ff;
      border-radius: 0.5rem;
      color: #0095ff;
      font: 400 0.8125rem/1 Open Sans, sans-serif;
      padding: 0.25rem 0.75rem;
    }
  `]
})
export class TopProducts {}