/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-organic-ranking",
  templateUrl: "./organic-ranking.component.html",
  styleUrls: ["./organic-ranking.component.scss"],
})
export class OrganicRankingComponent {}
