/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-organic-ranking",
  templateUrl: "./OrganicRanking.component.html",
  styleUrls: ["./OrganicRanking.component.scss"],
})
export class OrganicRankingComponent {}
