/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-target-vs-reality",
  templateUrl: "./target-vs-reality.component.html",
  styleUrls: ["./target-vs-reality.component.scss"],
})
export class TargetVsRealityComponent {}
