/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-top-products",
  templateUrl: "./TopProducts.component.html",
  styleUrls: ["./TopProducts.component.scss"],
})
export class TopProductsComponent {}
