/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-sales-overview",
  templateUrl: "./sales-overview.component.html",
  styleUrls: ["./sales-overview.component.scss"],
})
export class SalesOverviewComponent {}
