/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-sales-overview",
  templateUrl: "./SalesOverview.component.html",
  styleUrls: ["./SalesOverview.component.scss"],
})
export class SalesOverviewComponent {}
